<h1>Monstro da Semana 4: Mantícora</h1>

<h4><i>Bruno Bini Camargo</i></h4>

Neste notebook, serão resolvidos os exercícios 1, 2 e 3 do monstro Mantícora.

<h3>1. Qual a probabilidade de sortear duas cartas vermelhas em um baralho convencional (52 cartas)?</h3>

Primeiro precisamos saber quantas cartas vermelhas tem no baralho. O baralho é dividido em quatro naipes, sendo 2 deles pretos e os outros 2 vermelhos. Como há a mesma quantidade de cartas para cada naipe, podemos definir que 50% das cartas do baralho é vermelha, ou seja, são 26 cartas vermelhas.

Assim, a probabilidade $P(A)$ de ser sorteada uma carta vermelha do baralho é:

$$P(A) = \frac{26}{52} = \frac{1}{2}$$

Considerando retirada essa carta (sem reposição), a probabilidade $P(B)$ de outra carta vermelha ser sorteada é:

$$P(B) = \frac{25}{51}$$

Como queremos saber a probabilidade $P(C)$ do sorteio de *duas* cartas vermelhas, então devemos multiplicar $P(A)$ e $P(B)$:

$$P(C)= P(A) \times P(B) = \frac{26}{52} \times \frac{25}{51} = \frac{650}{2652} \approx 0.2451 \quad (24.51\%)$$

Resolvendo em Python:

In [1]:
total_cartas = 52
cartas_vermelhas = total_cartas/2

prob_primeira_carta = cartas_vermelhas/total_cartas
prob_segunda_carta = (cartas_vermelhas - 1)/(total_cartas - 1)

probabilidade = prob_primeira_carta * prob_segunda_carta

print(f"A probabilidade de sortear duas cartas vermelhas em um baralho convencional é:{probabilidade: .4f}, ou seja,{probabilidade * 100: .2f}%.")

A probabilidade de sortear duas cartas vermelhas em um baralho convencional é: 0.2451, ou seja, 24.51%.


Portanto, a probabilidade de sortear duas cartas vermelhas consecutivas e sem reposição é de aproximadamente 24.51% (ou cerca de $\frac{1}{4}$). A retirada da primeira carta vermelha reduz tanto o número de eventos favoráveis quanto o tamanho total do espaço amostral para o segundo sorteio.

<h3>2. Qual a probabilidade de sortear 5 cartas do mesmo naipe em um baralho convencional (52 cartas)?</h3>


O baralho é dividido em quatro naipes, cada um contendo o mesmo número de cartas. Assim, o número de cartas por naipe é:

$$Cartas_\text{naipe} = \frac{52}{4} = 13 \: \text{cartas}$$

Como o objetivo é obter cinco cartas de um mesmo naipe (sem fixar um naipe específico com antecedência), qualquer uma das 52 cartas do baralho pode ser sorteada no primeiro passo para definir qual será o naipe de referência. A probabilidade $P(A)$ de escolher essa primeira carta é:

$$P(A) = \frac{52}{52} = 1$$

Considerando retirada essa carta (sem reposição), o naipe já foi definido. Como restam 12 cartas desse mesmo naipe entre as 51 cartas restantes no baralho, a probabilidade $P(B)$ de a segunda carta pertencer ao mesmo naipe é:

$$P(B) = \frac{12}{51}$$

Percebe-se que, a cada nova retirada sem reposição, tanto o valor do numerador (cartas restantes do naipe) quanto o do denominador (total de cartas restantes no baralho) diminuem progressivamente em uma unidade, fazendo com que:

$$P(C) = \frac{11}{50}$$
$$P(D) = \frac{10}{49}$$
$$P(E) = \frac{9}{48}$$

Assim, a probabilidade $P(F)$ de todas elas pertencerem ao mesmo naipe é calculada multiplicando-se todas as probabilidades $P(A)$, $P(B)$, $P(C)$. $P(D)$ e $P(E)$:

$$P(F) = P(A) \times P(B) \times P(C)  \times P(D) \times P(E) = \frac{52}{52} \times \frac{12}{51} \times \frac{11}{50} \times \frac{10}{49} \times \frac{9}{48}$$

$$= \frac{12 \times 11 \times 10 \times 9}{51 \times 50 \times 49 \times 48} = \frac{11880}{5997600} = \frac{33}{16660} \approx 0.00198 \quad (0.198\%)$$

Resolvendo em Python:

In [2]:
total_cartas = 52   
qntd_naipes = 4
qntd_sorteios = 5
prob_total = 1.0

for i in range(1, qntd_sorteios):
    mesmo_naipe = (total_cartas / qntd_naipes) - i
    baralho = total_cartas - i
    prob_etapa = mesmo_naipe / baralho
    prob_total *= prob_etapa
    
print(f"A probabilidade de sortear cinco cartas do mesmo naipe em um baralho convencional é:{prob_total: .5f}, ou seja,{prob_total * 100: .3f}%.")

A probabilidade de sortear cinco cartas do mesmo naipe em um baralho convencional é: 0.00198, ou seja, 0.198%.


Conclui-se que a probabilidade de sortear 5 cartas consecutivas do mesmo naipe sem reposição é de aproximadamente 0.198%. A primeira carta atua como definidora do naipe de referência (com probabilidade igual a 1), enquanto as 4 retiradas subsequentes enfrentam uma redução progressiva tanto nos eventos favoráveis quanto no espaço amostral.

<h3>3. Qual a probabilidade de se ganhar na loteria federal comprando apenas um bilhete de 6 números?</h3>
    
<h3>A loteria federal sorteia 6 números inteiros diferentes no intervalo de [1, 60]. Um bilhete de 6 números te permite escolher 6 números diferentes dentro do intervalo. Ganhar, neste caso, significa que você acertou os 6 números sorteados.</h3>

Precisamos primeiro calcular o número total de combinações possíveis de 6 números (o espaço amostral) e verificar a probabilidadee de acertar a combinação sorteada. Como a ordem em que os números são sorteados não importa, utilizamos a fórmula de combinação:

$$C(n, k) = \frac{n!}{k!(n - k)!}$$

Sendo $n = 60$ e $k = 6$, calculamos:

$$C(60, 6) = \frac{60!}{6!(60 - 6)!} = \frac{60!}{6! \times 54!} = \frac{60 \times 59 \times 58 \times 57 \times 56 \times 55}{6 \times 5 \times 4 \times 3 \times 2 \times 1} = \frac{36045979200}{720} = 50063860$$

Como estamos considerando apenas um bilhete de 6 números, então o número de eventos favoráveis é 1. A probabilidade $P(A)$ é dada por:
  
$$P(A) = \frac{1}{C(60, 6)} = \frac{1}{50063860} \approx 1.997 \times 10^{-8} \quad (0.000001997\%)$$

Resolvendo em Python:

In [3]:
numero_total = 60
acertos_necessarios = 6

prob_final = 1.0

for i in range(acertos_necessarios):
    numerador = acertos_necessarios - i
    denominador = numero_total - i
    
    prob_final *= (numerador / denominador)

combinacoes = round(1 / prob_final)

print(f"A probabilidade de se ganhar na loteria federal comprando apenas um bilhete de 6 números é:{prob_final: .3e}, ou seja,{prob_final * 100: .9f}%.")

A probabilidade de se ganhar na loteria federal comprando apenas um bilhete de 6 números é: 1.997e-08, ou seja, 0.000001997%.


Conclui-se que o espaço amostral para a escolha de 6 números no intervalo [1, 60] resulta em $50063860$ combinações possíveis. Ao apostar um único bilhete simples, a chance de vitória é de aproximadamente $0.000001997\%$, evidenciando a baixíssima probabilidade matemática de acerto no prêmio principal com uma única aposta.

<h2>Interação com a IA</h2>

Nessa atividade, a IA foi utilizada para revisar as passagens algébricas, a fim de identificar eventuais erros matemáticos ou de notação.